//! FFI bindings to pq-crystals/dilithium reference implementation
//!
//! This module provides direct access to the official NIST reference
//! implementation for true NIST KAT verification.
//!
//! ## Why FFI?
//!
//! The pqcrypto-dilithium Rust crate is incompatible with the pq-crystals
//! reference implementation's KAT vectors. This is likely due to:
//! - Different domain separation tags
//! - Different signing modes (hedged vs deterministic)
//! - Different internal serialization
//!
//! By linking the reference implementation directly, we can verify
//! signatures generated by the reference code.

#![allow(non_camel_case_types)]
#![allow(dead_code)]

use std::os::raw::{c_int, c_uchar};

/// Dilithium3 parameters from FIPS 204
pub mod params {
    /// Public key size (bytes)
    pub const CRYPTO_PUBLICKEYBYTES: usize = 1952;
    /// Secret key size (bytes)
    pub const CRYPTO_SECRETKEYBYTES: usize = 4032;
    /// Signature size (bytes)
    pub const CRYPTO_BYTES: usize = 3309;
}

// FFI declarations for pq-crystals reference implementation
// These are only available when compiled with the pq_crystals_ffi feature
#[cfg(feature = "pq_crystals_ffi")]
extern "C" {
    /// Verify a signed message and extract the original message
    ///
    /// # Arguments
    /// * `m` - Output buffer for the message (must be at least smlen bytes)
    /// * `mlen` - Output: actual message length
    /// * `sm` - Signed message (signature || message)
    /// * `smlen` - Length of signed message
    /// * `ctx` - Context string (can be NULL for NIST KAT)
    /// * `ctxlen` - Length of context (0 for NIST KAT)
    /// * `pk` - Public key
    ///
    /// # Returns
    /// 0 on success (valid signature), -1 on failure
    fn pqcrystals_dilithium3_ref_open(
        m: *mut c_uchar,
        mlen: *mut usize,
        sm: *const c_uchar,
        smlen: usize,
        ctx: *const c_uchar,
        ctxlen: usize,
        pk: *const c_uchar,
    ) -> c_int;

    /// Verify a detached signature
    ///
    /// # Arguments
    /// * `sig` - Signature
    /// * `siglen` - Signature length (must be CRYPTO_BYTES)
    /// * `m` - Message
    /// * `mlen` - Message length
    /// * `ctx` - Context string (can be NULL for NIST KAT)
    /// * `ctxlen` - Length of context (0 for NIST KAT)
    /// * `pk` - Public key
    ///
    /// # Returns
    /// 0 on success (valid signature), -1 on failure
    fn pqcrystals_dilithium3_ref_verify(
        sig: *const c_uchar,
        siglen: usize,
        m: *const c_uchar,
        mlen: usize,
        ctx: *const c_uchar,
        ctxlen: usize,
        pk: *const c_uchar,
    ) -> c_int;
}

/// Result of FFI signature verification
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum VerifyResult {
    /// Signature is valid
    Valid,
    /// Signature is invalid
    Invalid,
    /// FFI not available (pq-crystals not compiled)
    NotAvailable,
}

/// Verify a signed message using the pq-crystals reference implementation
///
/// # Arguments
/// * `sm` - Signed message (signature || message)
/// * `pk` - Public key (1952 bytes)
///
/// # Returns
/// * `Ok((message, VerifyResult::Valid))` if signature is valid
/// * `Ok((vec![], VerifyResult::Invalid))` if signature is invalid
/// * `Ok((vec![], VerifyResult::NotAvailable))` if FFI is not available
pub fn verify_signed_message(sm: &[u8], pk: &[u8]) -> Result<(Vec<u8>, VerifyResult), String> {
    // Validate input sizes
    if pk.len() != params::CRYPTO_PUBLICKEYBYTES {
        return Err(format!(
            "Invalid public key size: expected {}, got {}",
            params::CRYPTO_PUBLICKEYBYTES,
            pk.len()
        ));
    }

    if sm.len() < params::CRYPTO_BYTES {
        return Err(format!(
            "Signed message too short: expected at least {}, got {}",
            params::CRYPTO_BYTES,
            sm.len()
        ));
    }

    #[cfg(feature = "pq_crystals_ffi")]
    {
        let mut m = vec![0u8; sm.len()];
        let mut mlen: usize = 0;

        let result = unsafe {
            pqcrystals_dilithium3_ref_open(
                m.as_mut_ptr(),
                &mut mlen,
                sm.as_ptr(),
                sm.len(),
                std::ptr::null(),
                0,
                pk.as_ptr(),
            )
        };

        if result == 0 {
            m.truncate(mlen);
            Ok((m, VerifyResult::Valid))
        } else {
            Ok((vec![], VerifyResult::Invalid))
        }
    }

    #[cfg(not(feature = "pq_crystals_ffi"))]
    {
        Ok((vec![], VerifyResult::NotAvailable))
    }
}

/// Verify a detached signature using the pq-crystals reference implementation
///
/// # Arguments
/// * `sig` - Signature (3309 bytes)
/// * `msg` - Message
/// * `pk` - Public key (1952 bytes)
///
/// # Returns
/// * `VerifyResult::Valid` if signature is valid
/// * `VerifyResult::Invalid` if signature is invalid
/// * `VerifyResult::NotAvailable` if FFI is not available
pub fn verify_detached(sig: &[u8], msg: &[u8], pk: &[u8]) -> Result<VerifyResult, String> {
    // Validate input sizes
    if pk.len() != params::CRYPTO_PUBLICKEYBYTES {
        return Err(format!(
            "Invalid public key size: expected {}, got {}",
            params::CRYPTO_PUBLICKEYBYTES,
            pk.len()
        ));
    }

    if sig.len() != params::CRYPTO_BYTES {
        return Err(format!(
            "Invalid signature size: expected {}, got {}",
            params::CRYPTO_BYTES,
            sig.len()
        ));
    }

    #[cfg(feature = "pq_crystals_ffi")]
    {
        let result = unsafe {
            pqcrystals_dilithium3_ref_verify(
                sig.as_ptr(),
                sig.len(),
                msg.as_ptr(),
                msg.len(),
                std::ptr::null(),
                0,
                pk.as_ptr(),
            )
        };

        if result == 0 {
            Ok(VerifyResult::Valid)
        } else {
            Ok(VerifyResult::Invalid)
        }
    }

    #[cfg(not(feature = "pq_crystals_ffi"))]
    {
        Ok(VerifyResult::NotAvailable)
    }
}

/// Check if FFI is available
pub fn is_ffi_available() -> bool {
    #[cfg(feature = "pq_crystals_ffi")]
    {
        true
    }

    #[cfg(not(feature = "pq_crystals_ffi"))]
    {
        false
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ffi_availability() {
        let available = is_ffi_available();
        println!("pq-crystals FFI available: {}", available);

        if !available {
            println!("NOTE: FFI not available. To enable:");
            println!("  1. Clone pq-crystals/dilithium to ../../pq-crystals-dilithium");
            println!("  2. Rebuild with: cargo build --features pq_crystals_ffi");
        }
    }

    #[test]
    #[cfg(feature = "pq_crystals_ffi")]
    fn test_ffi_verify_invalid_sizes() {
        // Test with invalid public key size
        let result = verify_detached(&[0u8; 3309], &[1, 2, 3], &[0u8; 100]);
        assert!(result.is_err());

        // Test with invalid signature size
        let result = verify_detached(&[0u8; 100], &[1, 2, 3], &[0u8; 1952]);
        assert!(result.is_err());
    }
}
