import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { RunReport } from './types.js';

function bullet(items: string[]): string {
  if (!items.length) return '_(none)_';
  return items.map((s) => `- ${s}`).join('\n');
}

export async function writeReport(runDir: string, report: RunReport): Promise<string> {
  await mkdir(runDir, { recursive: true });
  const jsonPath = resolve(runDir, 'report.json');
  const mdPath = resolve(runDir, 'report.md');

  await writeFile(jsonPath, JSON.stringify(report, null, 2));

  const sevCounts = report.quality_findings.reduce<Record<string, number>>(
    (acc, f) => ({ ...acc, [f.severity]: (acc[f.severity] ?? 0) + 1 }),
    {},
  );
  const layerLines = report.layer_results.map((r, idx) => {
    const a = report.layer_analyses[idx];
    return `| ${r.layer} | ${r.status} | ${r.exit_code} | ${r.duration_ms}ms | ${a?.confidence.toFixed(2) ?? '—'} | ${a?.issues.length ?? 0} |`;
  });

  const findingsLines = report.quality_findings
    .sort((a, b) => severityRank(a.severity) - severityRank(b.severity))
    .map(
      (f) => `- **[${f.severity}] ${f.title}** (_${f.source}_) — ${f.detail}`,
    );

  const proposalsLines = report.fixer_proposals.map(
    (p) => `- **[${p.risk}] ${p.id}: ${p.title}** — files: ${p.affected_files.join(', ')}`,
  );

  const md = `# E2E Orchestrator Run Report

**Sequence**: ${report.sequence}
**Started**: ${report.started_at}
**Finished**: ${report.finished_at}
**Duration**: ${(report.duration_ms / 1000).toFixed(1)}s
**Cost**: $${report.cost_usd.toFixed(4)} (input ${report.tokens.input}, cached ${report.tokens.cached_input}, output ${report.tokens.output})

## Verdict: ${report.final_verdict.verdict}

> ${report.final_verdict.summary}

- **Confidence**: ${report.final_verdict.confidence.toFixed(2)}
- **Fixer recommendation**: ${report.final_verdict.fixer_recommendation}
- **Must fix before merge**:
${bullet(report.final_verdict.must_fix_before_merge)}
- **Unresolved questions**:
${bullet(report.final_verdict.unresolved_questions)}

## Layer execution

| Layer | Status | Exit | Duration | Analyzer confidence | Issues |
|---|---|---|---|---|---|
${layerLines.join('\n')}

## Quality findings (Stage 3)

Counts by severity: ${Object.entries(sevCounts).map(([k, v]) => `${k}=${v}`).join(', ') || '_(none)_'}

${findingsLines.join('\n') || '_(none)_'}

## Fixer proposals (Stage 4)

${proposalsLines.join('\n') || '_(none)_'}

## Acceptance criteria (from Stage 1 plan)

${bullet(report.plan.acceptance_criteria)}

---
_Generated by quantum-shield-e2e-orchestrator_
`;

  await writeFile(mdPath, md);
  return mdPath;
}

function severityRank(s: string): number {
  switch (s) {
    case 'critical': return 0;
    case 'high': return 1;
    case 'medium': return 2;
    case 'low': return 3;
    case 'info': return 4;
    default: return 5;
  }
}
