//! SP1 guest: verify one SLH-DSA-SHAKE-128s signature.
//!
//! The test vector is embedded rather than read over zkVM I/O so the cycle
//! count measures the verification itself, not the host/guest plumbing.
//! Generated by `sphincs-m2`'s `emit_vector` example.

#![no_main]
#![no_std]

extern crate alloc;

sp1_zkvm::entrypoint!(main);

const MSG: &[u8] = include_bytes!("../../vectors/msg.bin");
const SIG: &[u8] = include_bytes!("../../vectors/sig.bin");
const PK: &[u8] = include_bytes!("../../vectors/pk.bin");

pub fn main() {
    let outcome = sphincs_m2::verify::slh_verify(MSG, SIG, b"", PK);
    assert!(outcome.valid, "the embedded vector must verify");
    sp1_zkvm::io::commit(&outcome.valid);
}
