//! SP1 guest: the FR-THRESH-1 statement.
//!
//! Verifies each submitted SPHINCS+ signature over `SHA3-256(lockId ‖
//! stateRoot)`, checks each signer's membership in the `ProverRegistry` active
//! set the claimed commitment covers, counts the ones that pass, and commits
//! the values `ThresholdProofVerifier` binds on-chain.
//!
//! The logic lives in `sphincs_m2::threshold` so it is testable on the host —
//! see `sphincs-m2/tests/threshold.rs`. This file is just the zkVM shell.
//!
//! The input is embedded rather than read over zkVM I/O so the cycle count
//! measures the statement, not host/guest plumbing. Generated by
//! `sphincs-m2`'s `emit_threshold_vector` example.

#![no_main]
#![no_std]

extern crate alloc;

sp1_zkvm::entrypoint!(main);

use sphincs_m2::threshold::{evaluate, ThresholdInput};

const INPUT: &[u8] = include_bytes!("../../vectors/threshold_input.bin");

pub fn main() {
    let input = ThresholdInput::decode(INPUT).expect("input must parse");
    let public_values = evaluate(&input).expect("signers must be well-ordered");

    // The exact 100 bytes `ThresholdProofVerifier.decodePublicValues` reads.
    sp1_zkvm::io::commit_slice(&public_values.encode());
}
