//! M2 measurement: take a **real** SLH-DSA-SHAKE-128s signature (generated by
//! the independent RustCrypto implementation), verify it with our
//! witness-emitting verifier, and prove the resulting Keccak permutation batch
//! with `p3-keccak-air`.
//!
//! Produces the NFR-3 (proof generation ≤ 1h p99) number for FR-THRESH-1, and
//! the real permutation count that sizes the M3 circuit.
//!
//! Run: `cargo run --release --example prove_verification`

use core::convert::Infallible;
use std::time::Instant;

use p3_challenger::{HashChallenger, SerializingChallenger64};
use p3_commit::ExtensionMmcs;
use p3_dft::Radix2DitParallel;
use p3_field::extension::BinomialExtensionField;
use p3_fri::{FriParameters, TwoAdicFriPcs};
use p3_goldilocks::Goldilocks;
use p3_keccak::{Keccak256Hash, KeccakF};
use p3_keccak_air::{generate_trace_rows, KeccakAir};
use p3_merkle_tree::MerkleTreeMmcs;
use p3_symmetric::{CompressionFunctionFromHasher, PaddingFreeSponge, SerializingHasher};
use p3_uni_stark::{prove, verify, StarkConfig};
use slh_dsa::{Shake128s, SigningKey, VerifyingKey};

use sphincs_m2::hash::shake256_parts;
use sphincs_m2::params::*;
use sphincs_m2::verify::slh_verify;

type Val = Goldilocks;
type Challenge = BinomialExtensionField<Val, 2>;
type ByteHash = Keccak256Hash;
type U64Hash = PaddingFreeSponge<KeccakF, 25, 17, 4>;
type FieldHash = SerializingHasher<U64Hash>;
type MyCompress = CompressionFunctionFromHasher<U64Hash, 2, 4>;
type ValMmcs = MerkleTreeMmcs<
    [Val; p3_keccak::VECTOR_LEN],
    [u64; p3_keccak::VECTOR_LEN],
    FieldHash,
    MyCompress,
    4,
>;
type ChallengeMmcs = ExtensionMmcs<Val, Challenge, ValMmcs>;
type Dft = Radix2DitParallel<Val>;
type Challenger = SerializingChallenger64<Val, HashChallenger<u8, ByteHash, 32>>;
type Pcs = TwoAdicFriPcs<Val, Dft, ValMmcs, ChallengeMmcs>;
type MyConfig = StarkConfig<Pcs, Challenge, Challenger>;

/// Deterministic RNG so the reported numbers are reproducible.
struct ShakeRng {
    seed: u64,
    counter: u64,
    buf: Vec<u8>,
    pos: usize,
}

impl ShakeRng {
    fn new(seed: u64) -> Self {
        Self { seed, counter: 0, buf: Vec::new(), pos: 0 }
    }

    fn next_byte(&mut self) -> u8 {
        if self.pos >= self.buf.len() {
            self.buf = shake256_parts(
                &[&self.seed.to_le_bytes(), &self.counter.to_le_bytes()],
                128,
                None,
            );
            self.counter += 1;
            self.pos = 0;
        }
        let b = self.buf[self.pos];
        self.pos += 1;
        b
    }
}

impl rand_core::TryRng for ShakeRng {
    type Error = Infallible;

    fn try_next_u32(&mut self) -> Result<u32, Infallible> {
        let mut b = [0u8; 4];
        self.try_fill_bytes(&mut b)?;
        Ok(u32::from_le_bytes(b))
    }

    fn try_next_u64(&mut self) -> Result<u64, Infallible> {
        let mut b = [0u8; 8];
        self.try_fill_bytes(&mut b)?;
        Ok(u64::from_le_bytes(b))
    }

    fn try_fill_bytes(&mut self, dst: &mut [u8]) -> Result<(), Infallible> {
        for slot in dst.iter_mut() {
            *slot = self.next_byte();
        }
        Ok(())
    }
}

impl rand_core::TryCryptoRng for ShakeRng {}

fn main() {
    // ---- permutation count over several real signatures ----
    println!("# M2: SLH-DSA-SHAKE-128s full verification witness");
    println!("# parameter set: n={N} h={H} d={D} a={A} k={K} w={W} len={LEN}");
    let fixed = 1 + K * (1 + A) + 3 + D * (5 + H_PRIME);
    println!("# structural fixed cost: {fixed} permutations (H_msg + FORS + T_k + per-layer T_len/tree)");

    let mut counts = Vec::new();
    let mut sample = None;
    for seed in 0..8u64 {
        let msg = format!("quantum shield prover attestation {seed}");
        let mut rng = ShakeRng::new(seed);
        let sk = SigningKey::<Shake128s>::new(&mut rng);
        let vk: VerifyingKey<Shake128s> = sk.as_ref().clone();
        let sig = signature::Signer::sign(&sk, msg.as_bytes());

        let out = slh_verify(
            msg.as_bytes(),
            &sig.to_bytes(),
            b"",
            &vk.to_bytes(),
        );
        assert!(out.valid, "oracle signature must verify");
        counts.push(out.trace.len());
        if sample.is_none() {
            sample = Some(out.trace.states);
        }
    }

    let min = *counts.iter().min().unwrap();
    let max = *counts.iter().max().unwrap();
    let avg = counts.iter().sum::<usize>() as f64 / counts.len() as f64;
    println!(
        "# measured permutations over {} signatures: min={min} avg={avg:.0} max={max}",
        counts.len()
    );

    // ---- prove the permutation batch of one real verification ----
    let states = sample.unwrap();
    let num_perms = states.len();
    let rows = (num_perms * 24).next_power_of_two();

    println!("# FRI: log_blowup=3 queries=100 pow=16 (multicore)");
    println!(
        "{:>8} | {:>10} | {:>12} | {:>12} | {:>14} | {:>7}",
        "perms", "rows", "prove_ms", "verify_ms", "proof_bytes", "ok"
    );

    let byte_hash = ByteHash {};
    let u64_hash = U64Hash::new(KeccakF {});
    let field_hash = FieldHash::new(u64_hash);
    let compress = MyCompress::new(u64_hash);
    let val_mmcs = ValMmcs::new(field_hash, compress);
    let challenge_mmcs = ChallengeMmcs::new(val_mmcs.clone());
    let dft = Dft::default();

    let fri_params = FriParameters {
        log_blowup: 3,
        log_final_poly_len: 0,
        num_queries: 100,
        commit_proof_of_work_bits: 16,
        query_proof_of_work_bits: 16,
        mmcs: challenge_mmcs,
    };

    let trace = generate_trace_rows::<Val>(states, fri_params.log_blowup);
    let pcs = Pcs::new(dft, val_mmcs, fri_params);
    let challenger = Challenger::from_hasher(vec![], byte_hash);
    let config = MyConfig::new(pcs, challenger);
    let air = KeccakAir {};

    let t0 = Instant::now();
    let proof = prove(&config, &air, trace, &[]);
    let prove_ms = t0.elapsed().as_secs_f64() * 1000.0;

    let size = bincode::serialize(&proof).map(|b| b.len()).unwrap_or(0);

    let t1 = Instant::now();
    let ok = verify(&config, &air, &proof, &[]).is_ok();
    let verify_ms = t1.elapsed().as_secs_f64() * 1000.0;

    println!(
        "{:>8} | {:>10} | {:>12.1} | {:>12.1} | {:>14} | {:>7}",
        num_perms, rows, prove_ms, verify_ms, size, ok
    );
}
