// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {ProverRegistry} from "@qs/ProverRegistry.sol";
import {RegistrySetCommitment} from "@qs/RegistrySetCommitment.sol";
import {ThresholdVerifier} from "@qs/ThresholdVerifier.sol";
import {Groth16WrapVerifier} from "@qs/Groth16WrapVerifier.sol";
import {SHA3_256} from "@qs/libraries/SHA3_256.sol";

/// @title Groth16WrapVerifierTest - real BN254 Groth16 proof on-chain
/// @notice The verifying key, proof and digest below are a golden fixture
///         generated by `src/crypto/circuits/wrap-groth16` (ark-groth16,
///         seed 0x515f6d3035): a real pairing-checked proof whose public
///         inputs are the halves of ThresholdVerifier's publicInputsDigest.
///         The Groth16 statement is the M0.5-impl placeholder; the
///         verification equation, calldata encoding and gas measured here
///         are what the real STARK-wrap circuit inherits unchanged.
contract Groth16WrapVerifierTest is Test {
    // ---- Fixture (wrap-groth16, seed 0x515f6d3035) ----
    bytes32 internal constant MESSAGE =
        0x7c883d94b532c1d17b06df350a07c4faade7e70605118bba9989b8d4370167ac;
    bytes internal constant PK_A =
        hex"ab334bc39c2d8b0a518722bd0c213bf5e3921e6cd7b75dd4d1c1935a6a2f2542";
    bytes internal constant PK_B =
        hex"2fd6adc9b8012df1f61c3311c17e0508fc8c9ac7ded471d83a4a32d424deecbd";
    bytes32 internal constant DIGEST =
        0x9c41779e0ef99dc2edbb636db5208213efd9f74a63e0ce922f044d2d22ed5698;

    Groth16WrapVerifier internal wrap;

    function vk() internal pure returns (uint256[20] memory k) {
        k[0] = 0x1eecdc02c1e4cf01295f2c4a62d7fc1922c31d0f3925291c85528a541b0eb124; // alpha.x
        k[1] = 0x05760a5fbbc2dbbcad088aeb6049a7f43e976c9375d27552c9192099778fc688; // alpha.y
        k[2] = 0x2ae95056edb47ce9d7512aeec3ab47cb76aaa3f319ba699b8c133a47aabd675f; // beta.x1
        k[3] = 0x0cc6c237d9cf86755c8ea477b76f9dbb8e721490109d24d3ef1b106b57278a7c; // beta.x0
        k[4] = 0x2591846cdccb694f0e68f28d5b797f1ab64d465bbca27489bfe6f19b929af380; // beta.y1
        k[5] = 0x2fe0d48189d988b1fd694bdc3e50c53d7b51be3fa59d5d7e798ee1a41c0a1cd6; // beta.y0
        k[6] = 0x0fe0131645683c36d36d0b2a20ff4595937f5bddf65c2c06ff5198fa7b6ae096; // gamma.x1
        k[7] = 0x22dbda9a7b3fcb93cecde63bfe5eeb5e9bcc0edf8383d1451253f48a9fb5f536; // gamma.x0
        k[8] = 0x1da27244240ce3146849f461ab2f91a764c33973217db23bf6c6e1f2158d530e; // gamma.y1
        k[9] = 0x102c36735e0a82271414cc4fb40ef67ddf1fffe668400ccdead900b8aad37c05; // gamma.y0
        k[10] = 0x12e4b1b5770d35c4e8685fb7bc4e1cececf7a8adb3d4fbf250d801783c4e9180; // delta.x1
        k[11] = 0x0f85de36b5ae1be92400cbc365c15d7456faa7900ba97031ea1562f105ec395f; // delta.x0
        k[12] = 0x1b01dd4908875eb9d0b6b742b686c845e8ed806b2a7718471a75c357694a54c4; // delta.y1
        k[13] = 0x04fc8b09160214a71cccfd040129e723ce0afdc80a5e72ed05364c2a1acd8309; // delta.y0
        k[14] = 0x24b04b8cab3df3b709c5183fdca4f6767264f00930589f24c4b623bec05f0966; // ic0.x
        k[15] = 0x077b8591219c48486f295044163756a322a2343b8a22a284f4f884fbea56361d; // ic0.y
        k[16] = 0x2b9a1511a181c67fbd631bbf170195f1707f29e51bcef43fece34deeaeb40e48; // ic1.x
        k[17] = 0x15254b4bcd9e4ac34927b31f5f97853bdccc3e6174315235ea7edf406d9fb43c; // ic1.y
        k[18] = 0x0493ae0a84ce9f8dc579ac357921a693b03d8c400cc2c1575b0c0816d460504f; // ic2.x
        k[19] = 0x10ffa8e06a14378381795c5ef09a1a7b9ff41b0c976cf8a9a22aefe867539b6a; // ic2.y
    }

    function proofBytes() internal pure returns (bytes memory) {
        uint256[8] memory p = [
            0x2cd28c945623247079b86168013c89509657dfc71d26c72197679505975d32f0, // A.x
            0x0e4d19ec7a2816d76612ef534437fb10856945da4b9282d0679dd95a946a9dcd, // A.y
            0x154f096b87a593131c8f09d0f118c7e5bdec8e95e291a962ad6a1ed4958e3644, // B.x1
            0x25e705ee1026b62db8ced475a3d9b635cf2c5fc7c13d2a6c982a2db4c2214fbc, // B.x0
            0x212e61662f3e319ae7b9452ff3d1318221746fd76e8185aff6f0b7a67b7fcb8e, // B.y1
            0x10b74ec57724f5f7003918d50de0b6686a3ee954e975e0620417ea2e6b928f83, // B.y0
            0x26db44e5e39e3991887878c3751ffd49a4601097b00b71d79a14320512651ac8, // C.x
            0x06b7f6eb5c529ed08c3da4d8673cc12ff8d16b1a62b809dcef7fd74a23388c59  // C.y
        ];
        return abi.encode(p);
    }

    function setUp() public {
        wrap = new Groth16WrapVerifier(vk());
    }

    function test_DigestMatchesFixture() public pure {
        bytes32 rebuilt =
            SHA3_256.hash(bytes.concat(abi.encodePacked(MESSAGE), PK_A, PK_B));
        assertEq(rebuilt, DIGEST, "on-chain digest must equal fixture digest");
    }

    function test_RealProofVerifies_withGas() public view {
        uint256 g0 = gasleft();
        bool ok = wrap.verifyWrapped(proofBytes(), DIGEST);
        uint256 used = g0 - gasleft();
        assertTrue(ok, "real Groth16 proof must verify");
        console2.log("verifyWrapped gas:", used);
        assertLt(used, 1_000_000, "NFR-2: wrap verification <= 1M gas");
    }

    function test_RejectsWrongDigest() public view {
        bytes32 bad = bytes32(uint256(DIGEST) ^ 1);
        assertFalse(wrap.verifyWrapped(proofBytes(), bad));
    }

    function test_RejectsMutatedProofA() public view {
        bytes memory p = proofBytes();
        p[31] = bytes1(uint8(p[31]) ^ 1); // flip a bit of A.x
        assertFalse(wrap.verifyWrapped(p, DIGEST));
    }

    function test_RejectsMutatedProofC() public view {
        bytes memory p = proofBytes();
        p[6 * 32 + 31] = bytes1(uint8(p[6 * 32 + 31]) ^ 1); // flip C.x
        assertFalse(wrap.verifyWrapped(p, DIGEST));
    }

    function test_RejectsWrongLength() public {
        vm.expectRevert(Groth16WrapVerifier.InvalidProofLength.selector);
        wrap.verifyWrapped(hex"deadbeef", DIGEST);
    }
}

/// @notice End-to-end: ProverRegistry -> RegistrySetCommitment ->
///         ThresholdVerifier -> Groth16WrapVerifier with the real proof.
contract ThresholdGroth16E2ETest is Test {
    bytes32 internal constant MESSAGE =
        0x7c883d94b532c1d17b06df350a07c4faade7e70605118bba9989b8d4370167ac;
    bytes internal constant PK_A =
        hex"ab334bc39c2d8b0a518722bd0c213bf5e3921e6cd7b75dd4d1c1935a6a2f2542";
    bytes internal constant PK_B =
        hex"2fd6adc9b8012df1f61c3311c17e0508fc8c9ac7ded471d83a4a32d424deecbd";

    ProverRegistry internal registry;
    RegistrySetCommitment internal commitment;
    ThresholdVerifier internal verifier;
    Groth16WrapVerifier internal wrap;

    function setUp() public {
        registry = new ProverRegistry(address(this), true);
        commitment = new RegistrySetCommitment(address(registry));
        verifier = new ThresholdVerifier(address(commitment), 2);
        wrap = new Groth16WrapVerifier(vkLocal());
        verifier.setWrapVerifier(address(wrap));

        registry.registerProverTestnet(address(0x1001), PK_A);
        registry.registerProverTestnet(address(0x1002), PK_B);
        commitment.snapshot();
    }

    function vkLocal() internal pure returns (uint256[20] memory k) {
        k[0] = 0x1eecdc02c1e4cf01295f2c4a62d7fc1922c31d0f3925291c85528a541b0eb124;
        k[1] = 0x05760a5fbbc2dbbcad088aeb6049a7f43e976c9375d27552c9192099778fc688;
        k[2] = 0x2ae95056edb47ce9d7512aeec3ab47cb76aaa3f319ba699b8c133a47aabd675f;
        k[3] = 0x0cc6c237d9cf86755c8ea477b76f9dbb8e721490109d24d3ef1b106b57278a7c;
        k[4] = 0x2591846cdccb694f0e68f28d5b797f1ab64d465bbca27489bfe6f19b929af380;
        k[5] = 0x2fe0d48189d988b1fd694bdc3e50c53d7b51be3fa59d5d7e798ee1a41c0a1cd6;
        k[6] = 0x0fe0131645683c36d36d0b2a20ff4595937f5bddf65c2c06ff5198fa7b6ae096;
        k[7] = 0x22dbda9a7b3fcb93cecde63bfe5eeb5e9bcc0edf8383d1451253f48a9fb5f536;
        k[8] = 0x1da27244240ce3146849f461ab2f91a764c33973217db23bf6c6e1f2158d530e;
        k[9] = 0x102c36735e0a82271414cc4fb40ef67ddf1fffe668400ccdead900b8aad37c05;
        k[10] = 0x12e4b1b5770d35c4e8685fb7bc4e1cececf7a8adb3d4fbf250d801783c4e9180;
        k[11] = 0x0f85de36b5ae1be92400cbc365c15d7456faa7900ba97031ea1562f105ec395f;
        k[12] = 0x1b01dd4908875eb9d0b6b742b686c845e8ed806b2a7718471a75c357694a54c4;
        k[13] = 0x04fc8b09160214a71cccfd040129e723ce0afdc80a5e72ed05364c2a1acd8309;
        k[14] = 0x24b04b8cab3df3b709c5183fdca4f6767264f00930589f24c4b623bec05f0966;
        k[15] = 0x077b8591219c48486f295044163756a322a2343b8a22a284f4f884fbea56361d;
        k[16] = 0x2b9a1511a181c67fbd631bbf170195f1707f29e51bcef43fece34deeaeb40e48;
        k[17] = 0x15254b4bcd9e4ac34927b31f5f97853bdccc3e6174315235ea7edf406d9fb43c;
        k[18] = 0x0493ae0a84ce9f8dc579ac357921a693b03d8c400cc2c1575b0c0816d460504f;
        k[19] = 0x10ffa8e06a14378381795c5ef09a1a7b9ff41b0c976cf8a9a22aefe867539b6a;
    }

    function proofBytes() internal pure returns (bytes memory) {
        uint256[8] memory p = [
            0x2cd28c945623247079b86168013c89509657dfc71d26c72197679505975d32f0,
            0x0e4d19ec7a2816d76612ef534437fb10856945da4b9282d0679dd95a946a9dcd,
            0x154f096b87a593131c8f09d0f118c7e5bdec8e95e291a962ad6a1ed4958e3644,
            0x25e705ee1026b62db8ced475a3d9b635cf2c5fc7c13d2a6c982a2db4c2214fbc,
            0x212e61662f3e319ae7b9452ff3d1318221746fd76e8185aff6f0b7a67b7fcb8e,
            0x10b74ec57724f5f7003918d50de0b6686a3ee954e975e0620417ea2e6b928f83,
            0x26db44e5e39e3991887878c3751ffd49a4601097b00b71d79a14320512651ac8,
            0x06b7f6eb5c529ed08c3da4d8673cc12ff8d16b1a62b809dcef7fd74a23388c59
        ];
        return abi.encode(p);
    }

    function signers() internal pure returns (ThresholdVerifier.SignerProof[] memory s) {
        // Height-1 tree over [leaf(PK_A), leaf(PK_B)]: each path is the
        // sibling leaf. PK_A sorts first by leaf hash (fixture guarantees).
        bytes32 leafA = SHA3_256.hash(PK_A);
        bytes32 leafB = SHA3_256.hash(PK_B);
        s = new ThresholdVerifier.SignerProof[](2);
        bytes32[] memory pathA = new bytes32[](1);
        pathA[0] = leafB;
        bytes32[] memory pathB = new bytes32[](1);
        pathB[0] = leafA;
        s[0] = ThresholdVerifier.SignerProof(PK_A, 0, pathA);
        s[1] = ThresholdVerifier.SignerProof(PK_B, 1, pathB);
    }

    function test_EndToEndThresholdWithRealGroth16() public view {
        uint256 g0 = gasleft();
        bool ok = verifier.verifyThreshold(MESSAGE, 0, signers(), proofBytes());
        uint256 used = g0 - gasleft();
        assertTrue(ok);
        console2.log("verifyThreshold total gas (2 signers, native membership):", used);
    }

    function test_EndToEndRejectsDifferentMessage() public {
        bytes32 other = bytes32(uint256(MESSAGE) ^ 1);
        vm.expectRevert(ThresholdVerifier.InvalidWrappedProof.selector);
        verifier.verifyThreshold(other, 0, signers(), proofBytes());
    }

    function test_EndToEndRejectsTamperedProof() public {
        bytes memory p = proofBytes();
        p[31] = bytes1(uint8(p[31]) ^ 1);
        vm.expectRevert(ThresholdVerifier.InvalidWrappedProof.selector);
        verifier.verifyThreshold(MESSAGE, 0, signers(), p);
    }
}
