// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {ProverRegistry} from "@qs/ProverRegistry.sol";
import {RegistrySetCommitment} from "@qs/RegistrySetCommitment.sol";

/// @title RegistrySetCommitmentTest - FR-THRESH-5 on-chain commitment
/// @notice The 5-prover fixture (public keys, leaves, root, paths) is a
///         golden vector generated by the circuit-side Rust implementation
///         (src/crypto/circuits/threshold-m3/src/bin/fixture.rs, `sha3`
///         crate FIPS 202 SHA3-256): the Solidity SHA3_256 library and tree
///         construction must reproduce it byte-for-byte, which is the
///         cross-stack guarantee that in-circuit membership proofs and this
///         contract anchor the same commitment C.
contract RegistrySetCommitmentTest is Test {
    ProverRegistry internal registry;
    RegistrySetCommitment internal commitment;

    // ---- Golden fixture (threshold-m3/src/bin/fixture.rs) ----
    bytes internal constant PK0 =
        hex"024f837cec77fdbdf35bb964dedbe803711a5770356d69c6efebf6de796c31f7";
    bytes internal constant PK1 =
        hex"444b8afdbbb097155e288d67d1f89a4750e73c4d031b2fc3206cce887e19c819";
    bytes internal constant PK2 =
        hex"d02dccb6761c84918d39644a3e16ba46f5b581f6b47157a747d25d6aca0beae0";
    bytes internal constant PK3 =
        hex"8f191f48b3eb9a320e48458ed9a0f5dc44248a1122d7bf1a11fb360a9a11f185";
    bytes internal constant PK4 =
        hex"bab757a108036f4bfad6e087330b5456614172bf8dabf067a65c82c8a59ee9a8";

    bytes32 internal constant GOLDEN_ROOT =
        0xf800ba3c7009802d0cd52ca9c004827160f6103bc5014ddb9d7c65605ce1c452;
    bytes32 internal constant GOLDEN_LEAF0 =
        0x87d856786b38316b73611460609f84222c96acd1cff92048b06136e31f8ce2a0;

    function setUp() public {
        registry = new ProverRegistry(address(this), true);
        commitment = new RegistrySetCommitment(address(registry));

        registry.registerProverTestnet(address(0x1001), PK0);
        registry.registerProverTestnet(address(0x1002), PK1);
        registry.registerProverTestnet(address(0x1003), PK2);
        registry.registerProverTestnet(address(0x1004), PK3);
        registry.registerProverTestnet(address(0x1005), PK4);
    }

    function path0() internal pure returns (bytes32[] memory p) {
        p = new bytes32[](3);
        p[0] = 0xd89d1c686112d674afa3298bc9b2b25b9acfd1ffd2f44826ed7175fd23e65006;
        p[1] = 0x39341aaca9b9768156ba42b2b682bc7e3f17f2e7d1d5ede2e5df774c9cd7cef2;
        p[2] = 0xe7fde6d42dd6ca1739e0d932c74abe6aee7b8f78dcb71e67b7c806b6ba3b10ab;
    }

    function path3() internal pure returns (bytes32[] memory p) {
        p = new bytes32[](3);
        p[0] = 0xe78c33e74ffacea97941f63593dc2abcb5914781263e7eb575c2d0a27b636ed4;
        p[1] = 0xfe42e3c994c0b4c5a92d7b48a665efc9f89ebf2f82fdacd5b293fad1f42e5612;
        p[2] = 0xe7fde6d42dd6ca1739e0d932c74abe6aee7b8f78dcb71e67b7c806b6ba3b10ab;
    }

    /// The on-chain snapshot must reproduce the Rust-computed golden root.
    function test_SnapshotMatchesCircuitGoldenRoot() public {
        (uint256 epoch, bytes32 root) = commitment.snapshot();
        assertEq(epoch, 0);
        assertEq(root, GOLDEN_ROOT, "on-chain root must equal circuit-side root");

        RegistrySetCommitment.Snapshot memory s = commitment.latest();
        assertEq(s.root, GOLDEN_ROOT);
        assertEq(s.proverCount, 5);
        assertEq(s.treeHeight, 3);
        assertEq(commitment.rootAt(0), GOLDEN_ROOT);
        assertEq(commitment.heightAt(0), 3);
    }

    function test_MembershipHonest() public {
        commitment.snapshot();
        assertTrue(commitment.verifyMembership(GOLDEN_ROOT, PK0, 0, path0()));
        assertTrue(commitment.verifyMembership(GOLDEN_ROOT, PK3, 3, path3()));
    }

    function test_MembershipRejectsWrongIndex() public view {
        assertFalse(commitment.verifyMembership(GOLDEN_ROOT, PK0, 1, path0()));
    }

    function test_MembershipRejectsNonMember() public view {
        bytes memory stranger =
            hex"00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff";
        assertFalse(commitment.verifyMembership(GOLDEN_ROOT, stranger, 0, path0()));
    }

    function test_MembershipRejectsForgedPath() public view {
        bytes32[] memory p = path0();
        p[1] = bytes32(uint256(p[1]) ^ 1);
        assertFalse(commitment.verifyMembership(GOLDEN_ROOT, PK0, 0, p));
    }

    /// A registry change (exit) must produce a different commitment at the
    /// next epoch while the old epoch stays queryable.
    function test_SnapshotEpochsTrackSetChanges() public {
        (, bytes32 root0) = commitment.snapshot();
        vm.prank(address(0x1005));
        registry.requestExit();
        (uint256 epoch1, bytes32 root1) = commitment.snapshot();
        assertEq(epoch1, 1);
        assertTrue(root0 != root1, "set change must change the commitment");
        assertEq(commitment.rootAt(0), root0);
        assertEq(commitment.snapshotCount(), 2);
    }
}
