import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { RunReport } from './types.js';

function bullet(items: string[]): string {
  if (!items.length) return '_(none)_';
  return items.map((s) => `- ${s}`).join('\n');
}

function emoji(verdict: string): string {
  switch (verdict) {
    case 'none': return '✅';
    case 'cosmetic': return '🟡';
    case 'regression': return '🔴';
    case 'broken': return '⛔';
    case 'unresolved': return '❓';
    default: return '⚪';
  }
}

export async function writeReport(runDir: string, report: RunReport): Promise<string> {
  await mkdir(runDir, { recursive: true });
  await writeFile(resolve(runDir, 'report.json'), JSON.stringify(report, null, 2));

  const captureLines = report.captures.map(
    (c) => `| ${c.viewport} | ${c.load_status} | ${c.baseline_path ? 'yes' : 'no'} | ${c.pixel_hash_match ?? '—'} |`,
  );
  const reviewLines = report.reviews.map(
    (r) => `| ${r.reviewer} | ${r.status} | ${r.findings.length} | ${r.confidence.toFixed(2)} |`,
  );
  const findingLines = report.reviews.flatMap((r) =>
    r.findings.map(
      (f) => `- **[${f.severity}] [${f.concern}] ${f.title}** — ${f.detail}`,
    ),
  );
  const patchLines = report.healer_proposals.map(
    (p) => `- **${p.id}: ${p.title}** (target: ${p.target}, risk: ${p.risk})`,
  );

  const md = `# UX Orchestrator Run Report

**Route**: ${report.route_id}
**Started**: ${report.started_at}
**Finished**: ${report.finished_at}
**Duration**: ${(report.duration_ms / 1000).toFixed(1)}s
**Plan source**: ${report.plan_source} ${report.plan_source === 'fallback' ? '(⚠ AI plan unavailable; static fallback used)' : ''}
**Cost**: $${report.cost_usd.toFixed(4)} (input ${report.tokens.input}, cached ${report.tokens.cached_input}, output ${report.tokens.output})

## Verdict: ${emoji(report.judge.verdict)} ${report.judge.verdict.toUpperCase()}

> ${report.judge.summary || '_(no summary)_'}

- **Confidence**: ${report.judge.confidence.toFixed(2)}
- **Designer review required**: ${report.judge.designer_review_required ? 'yes' : 'no'}
- **Final verifier**: ${report.final_verifier_status}
- **Must fix before ship**:
${bullet(report.judge.must_fix_before_ship)}
- **Unresolved questions**:
${bullet(report.judge.unresolved_questions)}

## Captures (Stage 2)

| Viewport | load_status | baseline | pixel_hash_match |
|---|---|---|---|
${captureLines.join('\n')}

## Reviewers (Stage 3)

| Reviewer | Status | Findings | Confidence |
|---|---|---|---|
${reviewLines.join('\n')}

### Findings (sorted by severity)

${findingLines.join('\n') || '_(none)_'}

## Healer proposals (Stage 5)

${patchLines.join('\n') || '_(none — verdict did not require healing)_'}

## Acceptance criteria (Stage 1)

${bullet(report.plan.acceptance_criteria)}

---
_Generated by quantum-shield-ux-orchestrator_
`;

  const mdPath = resolve(runDir, 'report.md');
  await writeFile(mdPath, md);
  return mdPath;
}
